---
title: "population structure figure production"
author: "Anita Wray"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

### Figure Production for Paper #2 on Pop Structure

##### Load required packages & color pals --------------------------------------
packages <- c('rnaturalearth', 'sf', 'patchwork', 'reshape', 'rnaturalearthdata',
              'dplyr', 'tidyverse','readxl', "multcompView", 'ggsignif', 'data.table', 
              'patchwork', 'ggOceanMaps', "tools", "dplyr", 'sp', 'readr',
              'mapproj', 'cowplot', 'stringr', 'PNWColors', 'wesanderson', 'vtable',
              'viridis', "nlme", 'lme4', 'car', 'emmeans')

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
theme_set(theme_classic())

#Set colors -- I don't use this anymore but keeping in case we go back
pal <- pnw_palette('Sunset2', 4)
pal_species <- wes_palette("Zissou1", 4)
color_pal_hybrids <- c('vermilion' = pal[1],
                       'sunset' = pal[3],
                       'SVH' = 'lightgreen')
color_pal_hybrids2 <- c('S' = pal[1],
                        'V-C' = '#FBCEB1',
                        'V-B' = '#FEBA4F',
                        'V-A' = '#F94D00',
                        'SVH' = 'lightgreen')

pal_pop_and_species <- pnw_palette('Cascades', 4)

pops_pal <- pnw_palette('Cascades', 3)
```

# Metadata filtering and processing

```{r metadata filtering and processing}

in_file <- "~/Desktop/VermilionRF/VMSURF Species ID/metadata/H&L-WCGBTS Combined_Vermilion RF Finclip Metadata_SK_051525_AW.xlsx"

#load in metadata
meta <- read_xlsx(in_file) 

#take a peek
table(meta$repunit)
table(meta$collection)

# remove non vermilion/sunset
meta <- meta %>%
  drop_na(`repunit`) %>%
  subset(`repunit` != 'rebs') %>%
  subset(`repunit` != 'bocaccio') %>%
  subset(`repunit` != 'canary')

#Change column names
names(meta)[names(meta) == 'Rubias Species Call'] <- 'repunit'
names(meta)[names(meta) == 'Rubias Pop Call'] <- 'collection'

#Make sure we have continuous variables
meta$Depth..m. <- as.numeric(meta$Depth..m.)
meta$LatDD <- as.numeric(meta$LatDD)
meta$LonDD.v2 <- as.numeric(meta$LonDD.v2)
meta$Fork.length..cm. <- as.numeric(meta$Fork.length..cm.)
meta$collection <- as.factor(meta$collection)
```
# Mapping
```{r mapping}

world <- ne_countries(scale = "large", returnclass = "sf")
path.eez.usa <- ("~/Desktop/VermilionRF/VMSURF Species ID/metadata/shapefiles/EEZ_land_union_v3_202003/")
fnam.eez.usa <- "EEZ_Land_v3_202030.shp"
eez.usa <- st_read(dsn = path.eez.usa, layer = file_path_sans_ext(fnam.eez.usa), quiet = T)
dat.eez.usa1 <- fortify(eez.usa)
labels <- read.csv(file = "~/Desktop/VermilionRF/VMSURF Species ID/metadata/paper2_labels.csv")
map_labels <- read.csv(file = "~/Desktop/VermilionRF/VMSURF Species ID/metadata/paper2_labels_2.csv")

# factor levels outside the plot to keep it clean
meta$repunit <- factor(meta$repunit, levels = c('vermilion', 'sunset'))

# Get states data as an sf object
states_map <- sf::st_as_sf(maps::map("state", plot = FALSE, fill = TRUE))

#all samples
map_passedsamples <- ggplot() +
  geom_sf(data = world, fill = "grey", color = "grey", inherit.aes = FALSE) +
  geom_sf(data = states_map, fill = NA, color = "grey50", inherit.aes = FALSE) +
  geom_point(data = meta, aes(x = LonDD.v2, y = LatDD, color = repunit)) +
  facet_wrap(~repunit) +
  coord_sf(xlim = c(-125.57, -115), ylim = c(30, 48.84), expand = FALSE) +
  scale_x_continuous(breaks = c(-124, -120, -116)) +
  scale_color_manual(values = pal_species) +
  theme(
    strip.background = element_blank(), 
    legend.position = 'none', 
    strip.text.x = element_text(size = 12, hjust = 0, face = "bold"),
    axis.title = element_blank())



#Splitting the dataset between vermilion and sunset to get a closer look
vermilion <- subset(meta, meta$repunit == 'vermilion')
sunset <- subset(meta, meta$repunit == 'sunset')
combined <- rbind(vermilion, sunset)

combined <- combined %>%
  mutate(across(repunit, factor, levels=c("vermilion","sunset")))

#edit 5/26 -- makes data a bit cleaner in the SCB
vermilion$rounded_lat <- round(vermilion$LatDD, digits = 1)
vermilion$rounded_lon <- round(vermilion$LonDD.v2, digits = 1)


## Plot the geographic distribution of the three populations of vermilion, 
#### which we colloquially called A,B, and C :)
vermilion_pop <- ggplot(data = vermilion) +
  geom_sf(data = dat.eez.usa1, size = 0.6, color = "grey", fill = 'white')+
  geom_sf(data = world, fill = "grey", color = "grey", inherit.aes = FALSE) +
  geom_sf(data = states_map, fill = NA, color = "grey50", inherit.aes = FALSE) +
  geom_text(data = labels, aes(label = label, x = long, y = lat), size.unit = 'mm', size = 2)+
  geom_segment(data = labels, 
               aes(x = start.arrow.long, y = start.arrow.lat, xend = end.arrow.long, yend = end.arrow.lat), 
               color = 'grey38', size = 0.45, arrow = arrow(length = unit(0.12, "cm"))) +
  geom_count(data = vermilion, aes(x = rounded_lon, y = rounded_lat, fill = `collection`), position = 'jitter', pch = 21) +
  coord_sf(xlim = c(-113, -128), ylim = c(29, 50.5), expand = FALSE)+
  scale_x_continuous(breaks = c(-126, -122, -118)) +
  facet_wrap(~collection)+
  scale_fill_viridis_d() +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    legend.title=element_blank(),
    legend.position = c(0.93, 0.78),
    legend.spacing = unit(0, "pt"),
    axis.title.x=element_blank(),
    axis.title.y=element_blank(),
    panel.border = element_rect(colour = "black", fill=NA),
    legend.background = element_blank(),
    legend.box.background = element_rect(colour = "black"),
    legend.text = element_text(size = 7))+
  geom_text(data = map_labels, aes(label = label, x= long, y = lat, angle = angle), color = 'grey80', size.unit = 'mm', size = 2)


vermilion_pop
```

# Vermilion PCA
```{r vermilion PCA}

meta_data <- read_tsv("~/Downloads/meta_data_unmerged_april_2024.tsv", show_col_types = FALSE) %>%
  dplyr::select(-unit) %>%
  filter(!(n()>1 & lane=="anita"), .by=sample_id) %>%
  mutate(collection_year=ifelse(is.na(collection_year), year(parse_date(collection_date, format="%m/%d/%Y")), collection_year)) %>%
  rename(long=start_longitude_dd, lat=start_latitude_dd) 
my_crs <- 3832
states <- ne_states(iso_a2 = c("MX", "CA", "US"), 
                    returnclass = "sf") %>%
  st_transform(crs = my_crs)
lakes <- ne_download(scale = 110, 
                     type = 'lakes', 
                     category = 'physical',
                     returnclass = "sf") %>%
  st_transform(crs = my_crs)

sample_table <- read_lines(str_c("~/Downloads/bamlist (1).txt")) %>%
  str_split(pattern = c("/"), simplify = TRUE) %>%
  .[,9] %>%
  as_tibble() %>%
  transmute(sample_name=str_remove(value, ".bam")) %>%
  separate(sample_name, into = c("sample_id", "unit"), remove = FALSE) %>%
  left_join(meta_data, by="sample_id") %>%
  dplyr::select(sample_name, sample_id, unit, lane, long, lat, collection_date, collection_year) %>%
  left_join(read_tsv("~/Downloads/locopipe_sample_table (2).tsv", show_col_types = FALSE) %>% dplyr::select(sample_name, population)) %>%
  mutate(population=case_when(population=="vermilion_1"~"V-C",
                              population=="vermilion_2"~"V-B",
                              population=="vermilion_3"~"V-A",))

meta_data <- read_tsv("~/Downloads/meta_data_unmerged_april_2024.tsv", show_col_types = FALSE) %>%
  dplyr::select(-unit) %>%
  filter(!(n()>1 & lane=="anita"), .by=sample_id) %>%
  mutate(collection_year=ifelse(is.na(collection_year), year(parse_date(collection_date, format="%m/%d/%Y")), collection_year)) %>%
  rename(long=start_longitude_dd, lat=start_latitude_dd) 


c <- read_delim("~/Downloads/combined.subsetted (1).cov", col_names = FALSE, delim = " ", show_col_types = FALSE) %>%
  as.matrix()

e <- eigen(c)
e_values <- e$values
var_explained <- round(e_values/sum(e_values)*100, 1)
fix_names <- function(x) str_c("PC", seq_along(x))
e_vectors <- as_tibble(e$vectors, .name_repair = fix_names) 
pca_table <- sample_table %>%
  bind_cols(e_vectors) %>%
  #dplyr::select(1:20) %>%
  mutate(long_original=long, lat_original=lat) %>%
  st_as_sf(coords = c("long", "lat")) %>%
  st_set_crs(4326) %>% 
  st_transform(crs = my_crs) %>%
  mutate(long=geometry %>% st_coordinates() %>% .[,"X"], lat=geometry %>% st_coordinates() %>% .[,"Y"]) %>%
  dplyr::select(-geometry)

## If we divide all samples into to groups based on an arbitrary cutoff along PC1, there is a subtle signal of the southern CA bight vs. other sites
verm_PCA <- pca_table %>%
  ggplot(aes(x=PC1, y=PC2, color=population)) +
  geom_point(shape=21, size=2, stroke=1) +
  labs(x=str_c("PC1 (", var_explained[1], "%)"),
       y=str_c("PC2 (", var_explained[2], "%)")) +
  scale_color_viridis_d() +
  theme_bw()+
  theme(legend.position = "none")


ggsave(file = "~/Desktop/VermilionRF/VMSURF Species ID/figures/pop_struct_MS/Fig1-PopulationMap_PCA.jpeg",
       width = 174,
       height = 230,
       units = c("mm"),
       dpi = 900)
verm_PCA + vermilion_pop + plot_annotation(tag_levels = 'a') + plot_layout(ncol = 1) & theme(plot.margin = margin(0.5,0.5,0.5,0.5))
dev.off()
```

# Looking at population overlap
```{r Do we see overlap in where these samples were caught?}
df <- as.data.frame(table(vermilion$Site.Cell.ID,vermilion$collection)) %>%
  pivot_wider(names_from = Var2, values_from = Freq ) %>%
  select(-c(S)) 

df <- df[-1,]

HL_df <- df[1:130,] %>%
  select(-c('V-A'))

non_HL_df <- df[130:142,]


df2 <- HL_df %>%
  pivot_longer(!Var1, names_to = "Pop", values_to = 'Count')

df3 <- non_HL_df %>%
  pivot_longer(!Var1, names_to = "Pop", values_to = 'Count')

unique(df2$Var1)

order <- c('Cambria', 'San Simeon', 'Piedras Blancas', 'Half Moon Bay',
           'Salmon Creek Beach', 'Gorda Rock', 'Brookings', 'Gold Beach',
           'Port Orford', 'Bandon', 'Depoe Bay', 'Strait of Juan de Fuca',
           'Kyuquot Sound, Canada')


df3 <- df3 %>%
  mutate(state = case_when(
  Var1 == 'Cambria' ~ 'CA',
  Var1 == 'San Simeon' ~ 'CA',
  Var1 == 'Piedras Blancas' ~ 'CA',
  Var1 == 'Half Moon Bay' ~ 'CA',
  Var1 == 'Salmon Creek Beach' ~ 'CA',
  Var1 == 'Gorda Rock' ~ 'CA',
  Var1 == 'Brookings' ~ 'OR',
  Var1 == 'Gold Beach' ~ 'OR',
  Var1 == 'Port Orford' ~ 'OR',
  Var1 == 'Cambria' ~ 'OR',
  Var1 == 'Bandon' ~ 'OR',
  Var1 == 'Depoe Bay' ~ 'OR',
  Var1 == 'Strait of Juan de Fuca' ~ 'WA',
  Var1 == 'Kyuquot Sound, Canada' ~ 'BC')
)


vermilion <- vermilion %>%
  mutate(collection_method = case_when(
    Survey == 'CB-ESA' ~ 'H&L',
    Survey == 'H&L' ~ 'H&L',
    Survey == 'Hyde Specimen' ~ 'PortSample',
    Survey == 'ODFW-Brookings' ~ 'PortSample',
    Survey == 'WDFW' ~ 'PortSample',
    Survey == 'WCGBTS' ~ 'Trawl'))


ggplot(data = df2, aes(y = Count, x = Var1)) +
  geom_bar(stat='identity', fill = 'grey')+
  facet_wrap(~Pop, ncol = 1, scales = "free") +
  xlab('Site Number') +
  theme(axis.text.x=element_text(angle=90, hjust=1))

ggplot(data = df3, aes(y = Count, x = Var1, color = state)) +
  geom_bar(stat='identity', fill = 'grey')+
  facet_wrap(~Pop, ncol = 1, scales = "free") +
  xlab('Site Number') +
  theme(axis.text.x=element_text(angle=45, hjust=1))+
  scale_x_discrete(limits = order)

gorda <- vermilion %>%
  subset(Site.Cell.ID == 'Gorda Rock')

table(gorda$collection, gorda$Year)
```

```{r Biological Characteristics between groups}
library(multcomp) ## load it here so we can still use select()

vermilion$Sex <- gsub('Female', 'F', vermilion$Sex )
vermilion$Sex <- gsub('Male', 'M', vermilion$Sex )
vermilion_with_sex <- subset(vermilion, vermilion$Sex != 'Unknown')

vermilion$collection <- gsub("V-A", "VA", vermilion$collection)
vermilion$collection <- gsub("V-B", "VB", vermilion$collection)
vermilion$collection <- gsub("V-C", "VC", vermilion$collection)

old <- ggplot(data = subset(vermilion, vermilion$Sex != ''),
       aes(x = `collection`, y = `Depth..m.`,
           col = `collection`)) +
  geom_boxplot()+
  theme(legend.position = 'none') +
  ylab('Depth (m)')+
  stat_summary(fun="mean") +
  scale_y_continuous(limits = c(0,200), n.breaks = 4, expand = c(0,0)) +
  scale_color_viridis_d() +
  theme(axis.title.x=element_blank())

pairwise.t.test(x = vermilion$Depth..m.,
                g = vermilion$`collection`)

youngings <- vermilion %>% 
  subset(Fork.length..cm. <= 35)
young <- ggplot(data = youngings,
       aes(x = `collection`, y = `Depth..m.`,
           col = `collection`)) +
  geom_boxplot()+
  theme(legend.position = 'none') +
  ylab('Depth (m)')+
  stat_summary(fun="mean") +
  scale_y_continuous(limits = c(0,200), n.breaks = 4, expand = c(0,0)) +
  scale_color_viridis_d()+
  theme(axis.title.x=element_blank())

pairwise.t.test(x = youngings$Depth..m.,
                g = youngings$`collection`)


sumtable(vermilion, group = 'collection', 
         vars = c("Depth..m.", "Fork.length..cm.", "Wt..kg.", "LatDD"),
         digits = 3, group.test = TRUE)

young+old

###### Weight versus collection
#vermilion <- vermilion %>%
#  subset(!is.na(Wt..kg.))

m1 <- lmer(data = vermilion,
           Wt..kg. ~ collection + (1 | Year) + (1 | collection_method))
AIC(m1)
m2 <- lmer(data = vermilion,
           Wt..kg. ~ collection + (1 | collection_method))
AIC(m2)
m3 <- lmer(data = vermilion,
           Wt..kg. ~ collection + (1 | Year))
AIC(m3)

m4 <- lm(data = vermilion,
           Wt..kg. ~ collection)
AIC(m4)

summary(m1)
Anova(m1)

logLik(m1)

ctm_obs.emm <- emmeans(m1, pairwise ~ collection, adjust = "tukey")

ctm_obs.emm

cld <- cld(ctm_obs.emm, alpha = 0.05, Letters = LETTERS)

# table with factors and 3rd quantile
wt_tbl <- group_by(vermilion, collection) %>%
  summarise(depth=mean(`Wt..kg.`, na.rm = T), sd = sd(`Wt..kg.`, na.rm = T))


# extracting the compact letter display and adding to the Tk table
wt_tbl$cld <- cld$.group

(weight <- ggplot(data = vermilion,
       aes(x = `collection`, y = `Wt..kg.`,
           col = `collection`)) +
  geom_boxplot()+
  theme(legend.position = 'none') +
  ylab('Weight (kg)')+
  stat_summary(fun.y="mean") +
  scale_color_viridis_d() +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 4.6))+
    theme(axis.title.x=element_blank(),
          text = element_text(size = 7.5))+
    geom_text(data = wt_tbl, aes(x = collection, y = c(4.4, 3.9, 4.0), label = cld), 
              size = 3, color = "black"))

##### Fork Length

m1 <- lmer(data = vermilion,
           Fork.length..cm. ~ collection + (1 | Year) + (1 | collection_method))
AIC(m1)
m2 <- lmer(data = vermilion,
           Fork.length..cm. ~ collection + (1 | collection_method))
AIC(m2)
m3 <- lmer(data = vermilion,
           Fork.length..cm. ~ collection + (1 | Year))
AIC(m3)


summary(m1)
Anova(m1)

ctm_obs.emm <- emmeans(m1, pairwise ~ collection, adjust = "tukey")

ctm_obs.emm

cld <- cld(ctm_obs.emm, alpha = 0.05, Letters = LETTERS)

# table with factors and 3rd quantile
length_tbl <- group_by(vermilion, collection) %>%
  summarise(depth=mean(`Fork.length..cm.`, na.rm = T), sd = sd(`Fork.length..cm.`, na.rm = T))


# extracting the compact letter display and adding to the Tk table
length_tbl$cld <- cld$.group


(length <- ggplot(data = vermilion,
       aes(x = `collection`, y = `Fork.length..cm.`,
           col = `collection`)) +
  geom_boxplot()+
  theme(legend.position = 'none') +
  ylab('Fork Length (cm)')+
  stat_summary(fun.y="mean") +
  scale_color_viridis_d()+
  scale_y_continuous(expand = c(0, 0), limits = c(0,75))+
  theme(axis.title.x=element_blank(),
        text = element_text(size = 7.5))+
  geom_text(data = length_tbl, aes(x = collection, y = c(69, 68, 68), label = cld), 
            size = 3, color = "black"))

### Depth 
m1 <- lmer(data = vermilion,
           Depth..m. ~ collection + (1 | Year) + (1 | collection_method))
summary(m1)
Anova(m1)

ctm_obs.emm <- emmeans(m1, pairwise ~ collection, adjust = "tukey")

ctm_obs.emm

cld <- cld(ctm_obs.emm, alpha = 0.05, Letters = LETTERS)

# table with factors and 3rd quantile
depth_tbl <- group_by(vermilion, collection) %>%
  summarise(depth=mean(`Depth..m.`, na.rm = T), sd = sd(`Depth..m.`, na.rm = T))


# extracting the compact letter display and adding to the Tk table
depth_tbl$cld <- cld$.group

#Depth total 
(depth <- ggplot(data = vermilion,
                aes(x = `collection`, y = `Depth..m.`,
                    col = `collection`)) +
  geom_boxplot()+
  theme(legend.position = 'none') +
  ylab('Depth (m)')+
  stat_summary(fun.y="mean") +
  scale_color_viridis_d() +
  scale_y_continuous(expand = c(0, 0), limits = c(0,200))+
  theme(axis.title.x=element_blank(),
        text = element_text(size = 7.5)) +
  geom_text(data = depth_tbl, aes(x = collection, y = c(68,128,173), label = cld), 
            size = 3, color = "black"))


scb <- (vermilion %>% subset(LatDD > 34.44 & LatDD < 42))

(depth_SCB <- ggplot(data = scb,
                 aes(x = `collection`, y = `Depth..m.`,
                     col = `collection`)) +
    geom_boxplot()+
    theme(legend.position = 'none') +
    ylab('Depth (m)')+
    stat_summary(fun.y="mean") +
    scale_color_viridis_d()+
    scale_y_continuous(expand = c(0, 0), limits = c(0,200))+
    theme(axis.title.x=element_blank(),
          text = element_text(size = 7.5)))


pop_biological <- depth + length + weight + plot_annotation(tag_levels = 'a')



ggsave(file = "~/Desktop/VermilionRF/VMSURF Species ID/figures/pop_struct_MS/Fig2-PopulationBiological.jpeg",
       width = 174,
       height = 90,
       units = c("mm"),
       dpi = 900)
pop_biological
dev.off()
```

# Look at some age stuff - not included in MS
```{r age analyses}
#Age
ggplot(data = vermilion,
       aes(x = `collection`, y = `Ages`,
           col = `collection`)) +
  geom_boxplot()+
  theme(legend.position = 'none') +
  ylab('Age (years)')+
  xlab('Population') +
  ggtitle('Age versus collection')+
  stat_summary(fun.y="mean") +
  scale_color_viridis_d()+
  scale_y_continuous(expand = c(0, 0))
```

# and some latitude stuff
```{r look at some latitude stuff}
ggplot(data = meta, aes(y = LatDD, x = Depth..m.)) +
  geom_point(alpha = 0.7, aes(col = collection)) +
  stat_smooth(method=lm)+
  scale_color_viridis(discrete = TRUE)

ggplot(data = meta, aes(y = LatDD, x = Depth..m., col = collection)) +
  geom_point(alpha = 0.7) +
  stat_smooth(method=lm)+
  facet_wrap(~collection)+
  scale_color_viridis(discrete = TRUE)

#dev.off()
```

```{r sunset PCA}
## for mapping
my_crs <- 3832
states <- ne_states(iso_a2 = c("MX", "CA", "US"), 
                    returnclass = "sf") %>%
  st_transform(crs = my_crs)
lakes <- ne_download(scale = 110, 
                     type = 'lakes', 
                     category = 'physical',
                     returnclass = "sf") %>%
  st_transform(crs = my_crs)

meta_data <- read_tsv("~/Downloads/meta_data_unmerged_april_2024.tsv", show_col_types = FALSE) %>%
  dplyr::select(-unit) %>%
  filter(!(n()>1 & lane=="anita"), .by=sample_id) %>%
  mutate(collection_year=ifelse(is.na(collection_year), year(parse_date(collection_date, format="%m/%d/%Y")), collection_year)) %>%
  rename(long=start_longitude_dd, lat=start_latitude_dd) 

sample_table <- read_lines(str_c("~/Downloads/bamlist.txt")) %>%
  str_split(pattern = c("/"), simplify = TRUE) %>%
  .[,9] %>%
  as_tibble() %>%
  transmute(sample_name=str_remove(value, ".bam")) %>%
  separate(sample_name, into = c("sample_id", "unit"), remove = FALSE) %>%
  left_join(meta_data, by="sample_id") %>%
  dplyr::select(sample_name, sample_id, unit, lane, long, lat, collection_date, collection_year) %>%
  mutate(location=case_when(lat>33.5~"northern",
                            lat<32~"southern",
                            TRUE~"central"),
         location=fct_relevel(location, c("northern", "central", "southern"))) %>%
  left_join(read_tsv("~/Downloads/locopipe_sample_table.tsv", show_col_types = FALSE) %>% dplyr::select(sample_name, population)) %>%
  mutate(population=case_when(population=="sunset_1"~"S-A",
                              population=="sunset_2"~"S-B"))


c <- read_delim("~/Downloads/combined.subsetted.cov", col_names = FALSE, delim = " ", show_col_types = FALSE) %>%
  as.matrix()
# c <- read_delim("../honeycomb_sunset_only/angsd/snp_calling_global/genome_hic_scaffold_19.covMat", col_names = FALSE) %>%
#   dplyr::select(., -ncol(.)) %>%
#   as.matrix()
e <- eigen(c)
e_values <- e$values
var_explained <- round(e_values/sum(e_values)*100, 1)
fix_names <- function(x) str_c("PC", seq_along(x))
e_vectors <- as_tibble(e$vectors, .name_repair = fix_names) 
pca_table <- sample_table %>%
  bind_cols(e_vectors) %>%
  #dplyr::select(1:20) %>%
  mutate(long_original=long, lat_original=lat) %>%
  st_as_sf(coords = c("long", "lat")) %>%
  st_set_crs(4326) %>% 
  st_transform(crs = my_crs) %>%
  mutate(long=geometry %>% st_coordinates() %>% .[,"X"], lat=geometry %>% st_coordinates() %>% .[,"Y"]) %>%
  dplyr::select(-geometry)

## If we divide all samples into to groups based on an arbitrary cutoff along PC1, there is a subtle signal of the southern CA bight vs. other sites
PCA <- pca_table %>%
  ggplot(aes(x=PC1, y=PC2, color=lat_original)) +
  geom_point(shape=21, size=2, stroke=1) +
  scale_color_viridis_c(option = "B", direction=-1, end=0.9, name="latitude") +
  geom_vline(xintercept=0.061) +
  annotate("text", x=0.061+0.04, y=0.2, label="S-A", size=5) +
  annotate("text", x=0.061-0.04, y=0.2, label="S-B", size=5) +
  theme_bw() +
  theme(legend.position = c(0.915, 0.27),
        legend.box.background = element_rect(colour = "black"),
        legend.background = element_blank(),) +
  xlab(paste0("PC1 (",var_explained[1],"%)", collapse = "")) + 
  ylab(paste0("PC2 (",var_explained[2],"%)", collapse = ""))


ggsave(file = "~/Desktop/VermilionRF/VMSURF Species ID/figures/pop_struct_MS/Fig3-SunsetPCA.jpeg",
       width = 174,
       height = 110,
       units = c("mm"),
       dpi = 900)
PCA
dev.off()
```
